server:
  port: ${SERVER_PORT:8000}

swagger:
  host: ${SWAGGER_ADDRESS:localhost:${SERVER_PORT:8000}}
  basePackage: com.am.skillmaker
  title: API Skill Maker
  description: API Skill Maker

spring:
  application.name: "skill-maker"
  main.allow-bean-definition-overriding: true
  jackson:
    serialization:
      fail-on-empty-beans: false
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
  datasource:
    #    ${DB_HOST:localhost}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:skill-maker}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    driverClassName: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/changelog.xml
    enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: validate
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
      format_sql: ${FORMAT_SQL:false}
      enable_lazy_load_no_trans: true
    show-sql: ${SHOW_SQL:true}
    open-in-view: false
  mvc:
    log-resolved-exception: true
    pathmatch:
      matching-strategy: ant_path_matcher
#attachment:
#  apiKey: 6d207e02198a847aa98d0a2a901485a5
#  host: https://freeimage.host/api/1/upload